import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";

const font = Overpass({
  variable: "--font-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta charSet="UTF-8"></meta>
      <body className={`${font.variable} antialiased`}>{children}</body>
    </html>
  );
}
